### ISSUE TITLE
Version mismatch?

### ISSUE THREAD

**Issue by schmittx** [wardcraigj/total-connect-client#1]
I've tried configuring the TotalConnect alarm control panel within Home Assistant but am getting an error that it cannot find this dependency. I think it's due to a version mismatch (looking for "0.7" but setup shows "0.07")?

Can you help at all?

**Comment by wardcraigj** [comment]
Interesting... It's registered in pypi as 0.7 so hass should be able to find it. What happens if you try running `pip install total-connect-client==0.7`?

**Comment by schmittx** [comment]
Running that command seems to work, but I still get an error when starting HAss. I'm not much of a dev so I'm outta my element here...could it be a name mismatch (hyphen vs. underscore)?

Below is error log from HAss.

`17-04-11 10:14:38 ERROR (MainThread) [homeassistant.setup] Not initializing alarm_control_panel.totalconnect because could not install dependency total_connect_client==0.7
17-04-11 10:14:38 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alarm_control_panel.totalconnect: Could not install all requirements.`

**Comment by wardcraigj** [comment]
ah, yeah that's probably exactly what it is. Do you know where totalconnect.py and requirements_all.txt are located in your hass install? if you do, you can try changing the underscores to hyphens there and see if that works for you, or in your config folder you could paste the changed component in as a custom component

```
"""Interfaces with TotalConnect alarm control panels."""
import logging

import voluptuous as vol

import homeassistant.components.alarm_control_panel as alarm
from homeassistant.components.alarm_control_panel import PLATFORM_SCHEMA
from homeassistant.const import (
    CONF_PASSWORD, CONF_USERNAME, STATE_ALARM_ARMED_AWAY,
    STATE_ALARM_ARMED_HOME, STATE_ALARM_DISARMED, STATE_UNKNOWN,
    CONF_NAME)
import homeassistant.helpers.config_validation as cv

REQUIREMENTS = ['total-connect-client==0.7']

_LOGGER = logging.getLogger(__name__)

DEFAULT_NAME = 'Total Connect'

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({
    vol.Required(CONF_PASSWORD): cv.string,
    vol.Required(CONF_USERNAME): cv.string,
    vol.Optional(CONF_NAME, default=DEFAULT_NAME): cv.string,
})


def setup_platform(hass, config, add_devices, discovery_info=None):
    """Setup a TotalConnect control panel."""
    name = config.get(CONF_NAME)
    username = config.get(CONF_USERNAME)
    password = config.get(CONF_PASSWORD)

    total_connect = TotalConnect(name, username, password)
    add_devices([total_connect], True)


class TotalConnect(alarm.AlarmControlPanel):
    """Represent an TotalConnect status."""

    def __init__(self, name, username, password):
        """Initialize the TotalConnect status."""
        from total_connect_client import TotalConnectClient

        _LOGGER.debug('Setting up TotalConnect...')
        self._name = name
        self._username = username
        self._password = password
        self._state = STATE_UNKNOWN
        self._client = TotalConnectClient.TotalConnectClient(username,
                                                             password)

    @property
    def name(self):
        """Return the name of the device."""
        return self._name

    @property
    def state(self):
        """Return the state of the device."""
        return self._state

    def update(self):
        """Return the state of the device."""
        status = self._client.get_armed_status()

        if status == self._client.DISARMED:
            state = STATE_ALARM_DISARMED
        elif status == self._client.ARMED_STAY:
            state = STATE_ALARM_ARMED_HOME
        elif status == self._client.ARMED_AWAY:
            state = STATE_ALARM_ARMED_AWAY
        else:
            state = STATE_UNKNOWN

        self._state = state

    def alarm_disarm(self, code=None):
        """Send disarm command."""
        self._client.disarm()

    def alarm_arm_home(self, code=None):
        """Send arm home command."""
        self._client.arm_stay()

    def alarm_arm_away(self, code=None):
        """Send arm away command."""
        self._client.arm_away()

```

**Comment by wardcraigj** [comment]
you could also just try updating off this branch fix and see, if that's easier:
`pip3 install --upgrade git+git://github.com/wardcraigj/home-assistant.git@tc-fix`

I'm not at home at the moment so I can't really test this, but I suspect it should fix your issue

**Comment by schmittx** [comment]
Sounds good, I'm trying to locate requirements_all.txt but not having any luck.

I installed HASS via Hassbian image (runs HASS in a virtual environment), any advice on where to find it?

**Comment by wardcraigj** [comment]
I'm not too sure-- it might not even be necessary to find and change that file to be honest, it could only exist in dev. Do you get the same error if you try to run hass by just changing totalconnect.py?

**Comment by schmittx** [comment]
Changing only totalconnet.py gives me the following errors.

```
17-04-11 11:05:32 ERROR (MainThread) [homeassistant.setup] Not initializing alarm_control_panel.totalconnect because could not install dependency total-connect-client==0.7
17-04-11 11:05:32 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alarm_control_panel.totalconnect: Could not install all requirements.
```

**Comment by wardcraigj** [comment]
hmm, what about running it off this branch? You'd have to activate the virtualenv and then run this upgrade:

`pip3 install --upgrade git+git://github.com/wardcraigj/home-assistant.git@tc-fix`

**Comment by schmittx** [comment]
Nope, still produces same error...

**Comment by wardcraigj** [comment]
strange. Sorry I can't diagnose this quicker. I'm not at home at the moment so if we don't get this solved shortly, I should be able to poke at it a bit easier later this evening.

I wonder if you can try running 0.5 as a custom component?

As your homeassistant user, if you go to the directory where your config is and make a dir called custom_components/alarm_control_panel and put a file called totalconnect.py in it with the following code:
```

"""

Interfaces with Alarm.com alarm control panels.

For more details about this platform, please refer to the documentation at
https://home-assistant.io/components/alarm_control_panel.alarmdotcom/
"""
import logging
import asyncio
import voluptuous as vol
import homeassistant.components.alarm_control_panel as alarm
from homeassistant.components.alarm_control_panel import PLATFORM_SCHEMA
from homeassistant.const import (
    CONF_PASSWORD, CONF_USERNAME, STATE_ALARM_ARMED_AWAY,
    STATE_ALARM_ARMED_HOME, STATE_ALARM_DISARMED, STATE_UNKNOWN,
    CONF_NAME)
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.aiohttp_client import async_get_clientsession

REQUIREMENTS = ['total_connect_client==0.5']

_LOGGER = logging.getLogger(__name__)

DEFAULT_NAME = 'total-connect-client'

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend({
    vol.Required(CONF_PASSWORD): cv.string,
    vol.Required(CONF_USERNAME): cv.string,
    vol.Optional(CONF_NAME, default=DEFAULT_NAME): cv.string,
})


@asyncio.coroutine
def async_setup_platform(hass, config, async_add_devices, discovery_info=None):
    """Setup a Alarm.com control panel."""
    name = config.get(CONF_NAME)
    username = config.get(CONF_USERNAME)
    password = config.get(CONF_PASSWORD)

    total_connect = TotalConnect(hass, name, username, password)
    async_add_devices([total_connect])


class TotalConnect(alarm.AlarmControlPanel):
    """Represent an Alarm.com status."""

    def __init__(self, hass, name,  username, password):
        """Initialize the Alarm.com status."""
        from total_connect_client import TotalConnectClient

        _LOGGER.debug('Setting up TotalConnect...')
        self._hass = hass
        self._name = name
        self._username = username
        self._password = password
        self._state = STATE_UNKNOWN
        self._client = TotalConnectClient.TotalConnectClient(username, password)

    @property
    def name(self):
        """Return the name of the device."""
        return self._name

    @property
    def state(self):
        """Return the state of the device."""
        return self._state

    def update(self):
        """Return the state of the device."""
        status = self._client.get_armed_status()

        if status == self._client.DISARMED:
            state = STATE_ALARM_DISARMED
        elif status == self._client.ARMED_STAY:
            state = STATE_ALARM_ARMED_HOME
        elif status == self._client.ARMED_AWAY:
            state = STATE_ALARM_ARMED_AWAY
        else:
            state = STATE_UNKNOWN

        self._state = state

    def alarm_disarm(self, code=None):
        """Send disarm command."""
        self._client.disarm()

    def alarm_arm_home(self, code=None):
        """Send arm home command."""
        self._client.arm_stay()

    def alarm_arm_away(self, code=None):
        """Send arm away command."""
        self._client.arm_away()
```

**Comment by schmittx** [comment]
Not a problem at all, I appreciate the help and quick responses.

I'm away from home now too so I won't be able to mess with it much until end of this week.

I tried copy/pasting totalconnect.py from hass components to custom components while also changing the total-connect-client naming, but still got the same error.

I'll be glad to help later this week though, thanks for your work on this...super anxious to get this working as it's been on my wish list for months now!

**Comment by schmittx** [comment]
Just tried running 0.5 as a custom component with no luck. I tried both as you pasted and also after changing "total_connect_client==0.5" to "total-connect-client==0.5", no luck either way (running HASS 0.42.3).

**Comment by wardcraigj** [comment]
Weird. I just cloned the hass master branch and spun up a fresh vagrant virtual box and ran the install and the package came down and loaded.

Is it possible that you the only thing that I can think of is that maybe the when the upgrade was run, it was run under the correct user but the virtualenv wasn't activated?

**Comment by schmittx** [comment]
Good suggestion, I'll try upgrading to 0.42.4 while making sure to activate virtual env. It'll have to wait until tomorrow though, I'll keep you posted.

**Comment by schmittx** [comment]
I was finally able to diagnose the problem and get this installed successfully.

It turns out I needed to install "libxml2-dev" and "libxmlsec1-dev" to allow "total_connect_client==0.7" to fully install.

Not sure what those packages are, but it worked...ha!

Thanks again for the help!

**Comment by wardcraigj** [comment]
Great! Thanks! I'll update the HASS docs since other users might run into this issue as well! Thanks again!
