### ISSUE TITLE
'No security panel found' exception

### ISSUE THREAD

**Issue by phileaton** [wardcraigj/total-connect-client#11]
I get a 'No security panel found' exception with my system (L5100-WiFi) similar to what was reported with issue #5. The problem seems to be from the hard coding of the panel name in get_security_panel_device_id(self, location):

https://github.com/wardcraigj/total-connect-client/blob/5d58d90acbc415f785eae0772ba6af5e94926f60/total_connect_client/TotalConnectClient.py#L145

My panel name is 'L5100-WiFi'. Changing the code as follows fixes the problem:

` if device['DeviceName'] == 'Security Panel' or device['DeviceName'] == 'Security System' or device['DeviceName'] == 'L5100-WiFi': `

**Comment by wardcraigj** [comment]
Thanks for the PR #12 ! Closing!
